### ISSUE TITLE
AttributeError: module 'urllib3' has no attribute 'disable_warnings'

### ISSUE THREAD

**Issue by bossjac** [EnableSecurity/wafw00f#138]
**Describe the bug**
AttributeError: module 'urllib3' has no attribute 'disable_warnings'

**Expected behavior**
run wafw00f and discover waf type

**Desktop:**
 - OS: Kali Linux
 - OS version, distribution: 2021.2
 - Python version: 3.9.2

**Debug output**
Traceback (most recent call last):
  File "/usr/bin/wafw00f", line 4, in <module>
    from wafw00f import main
  File "/usr/lib/python3/dist-packages/wafw00f/main.py", line 21, in <module>
    from wafw00f.lib.evillib import urlParser, waftoolsengine, def_headers
  File "/usr/lib/python3/dist-packages/pluginbase.py", line 438, in plugin_import
    return self._system_import(import_name, globals, locals,
  File "/usr/lib/python3/dist-packages/wafw00f/lib/evillib.py", line 26, in <module>
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
**AttributeError: module 'urllib3' has no attribute 'disable_warnings**

**Comment by 0xInfection** [comment]
Hey @bossjac, thanks for pulling an issue up. I'm not able to reproduce this issue, I got a fresh Kali distro which has wafw00f built-in and here's my output:

![image](https://user-images.githubusercontent.com/39941993/129468965-e35210d7-52ed-42f8-8a05-2cda5ba1f6e8.png)

Not sure how you ran into this. Can you give some more info on how you installed the wafw00f? Did the pre-installed one give you an error, or did you install it yourself?

**Comment by bossjac** [comment]
No, I also get a fresh Kali Linux distro it was installed automatically, I don't have any such more info.

**Comment by sandrogauci** [comment]
I also tested kali v2021.2.0 and was not able to reproduce the issue. The error `AttributeError: module 'urllib3' has no attribute 'disable_warnings` indicates a broken or different version of urllib3, one that doesn't include `disable_warnings`. 

On the default kali, if I run the following: `python3.9 -c 'import urllib3; print(urllib3._version.__version__)'`

I get: `1.25.10`.

Going to close this because we cannot reproduce it and it seems like something specific to your setup.

My suggestion is:

- setup kali again and try again
- if you intend to reopen this issue, please tell us all steps you took to get to the error (including how you are getting kali, how you are running it etc) and the version of `urllib3`.
