### ISSUE TITLE
join forces

### ISSUE THREAD

**Issue by blshkv** [EnableSecurity/wafw00f#87]
guys,

I see two tools doing the same thing written using the same language.
Why don't you join forces?

https://github.com/Ekultek/WhatWaf

Thanks

**Comment by Ekultek** [comment]
I’m game if you are.

**Comment by sandrogauci** [comment]
Thanks for the suggestion and interest! We're not currently looking at expand the feature-set beyond WAF detection. I think there is already a bit of "passive collaboration" since some of the detection code is shared and that's totally fine. Improvements to our detection code are of course welcome via pull requests :)

**Comment by Ekultek** [comment]
@sandrogauci I'll improve yours if you improve mine as well ;p

**Comment by blshkv** [comment]
FYI, https://github.com/Ekultek @Ekultek went missing, he deleted his account.
So the problem solved.

**Comment by Ekultek** [comment]
Was there really ever an issue though..?

**Comment by sandrogauci** [comment]
Not at all.
