### ISSUE TITLE
Sanitized Output

### ISSUE THREAD

**Issue by sonawanesarvesh** [EnableSecurity/wafw00f#93]
i wanted to know how can i get sanitized output - with clear indication whether WAF is detected or not (instead of graphical representations of WAFW00F logo/ dog image and other stuff - i want simple - WAF detected = Yes/No - if detected then name of WAF)

**Comment by 0xInfection** [comment]
Hi @sonawanesarvesh,

You could try the following:
- Describing your problem in detail without being too sentimental/childish about it.
- Attaching screenshots/copy-pasting your output where the problem is occurring using the`-vv` flag.
- Using a ANSI sequence supporting terminal (a Linux terminal) so that you can look out for the name of the detected WAF (if any) when it is being highlighted with colours.
- Trying to read the output of the tool on the terminal properly.

Feel free to reopen this issue, when you've tried the above-mentioned. Until then, I'm holding off this issue as it does not have the sufficent information which qualifies for a valid issue/bug report.

**Comment by sandrogauci** [comment]
Thought I'd followup a little bit to add that I think @sonawanesarvesh would like simple output that could be easily fed to something else without having to parse the wafw00f fancy output.

We might be adding file output functionality which I think, would serve the purpose pretty well. And perhaps, this output could be sent to stdout. I think this would address @sonawanesarvesh 's need.

**Comment by sonawanesarvesh** [comment]
@sandrogauci 
Thank you for correcting my response, exactly this is what i am expecting.
I want to pick the wafw00f output and feed it to analytics tool, for this i need clean stdout response

**Comment by 0xInfection** [comment]
WIP: #95

**Comment by 0xInfection** [comment]
Fixed in #96.
